// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MoviesHD.EpisodeSourceModel;
//
//    var episodeSourceModel = EpisodeSourceModel.FromJson(jsonString);

namespace MoviesHD.EpisodeSourceModel
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class EpisodeSourceModel
    {
        [JsonProperty("data")]
        public List<Datum> Data { get; set; }
    }

    public partial class Datum
    {
        [JsonProperty("episode")]
        public long Episode { get; set; }

        [JsonProperty("episodes_include")]
        public string EpisodesInclude { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("rating")]
        public double Rating { get; set; }

        [JsonProperty("poster")]
        public Uri Poster { get; set; }

        [JsonProperty("covers")]
        public Dictionary<string, Uri> Covers { get; set; }

        [JsonProperty("files")]
        public List<DatumFile> Files { get; set; }
    }

    public partial class DatumFile
    {
        [JsonProperty("lang")]
        public string Lang { get; set; }

        [JsonProperty("files")]
        public List<FileFile> Files { get; set; }

        [JsonProperty("subtitles")]
        public List<Subtitle> Subtitles { get; set; }
    }

    public partial class FileFile
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("quality")]
        public string Quality { get; set; }

        [JsonProperty("src")]
        public Uri Src { get; set; }

        [JsonProperty("duration")]
        public long Duration { get; set; }

        [JsonProperty("thumbnails")]
        public List<Thumbnail> Thumbnails { get; set; }
    }

    public partial class Thumbnail
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("start_time")]
        public long StartTime { get; set; }

        [JsonProperty("end_time")]
        public long EndTime { get; set; }

        [JsonProperty("duration")]
        public long Duration { get; set; }

        [JsonProperty("interval")]
        public long Interval { get; set; }

        [JsonProperty("width")]
        public long Width { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }

        [JsonProperty("columns")]
        public long Columns { get; set; }
    }

    public partial class Subtitle
    {
        [JsonProperty("lang")]
        public string Lang { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }
    }

    public partial class EpisodeSourceModel
    {
        public static EpisodeSourceModel FromJson(string json) => JsonConvert.DeserializeObject<EpisodeSourceModel>(json, MoviesHD.EpisodeSourceModel.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this EpisodeSourceModel self) => JsonConvert.SerializeObject(self, MoviesHD.EpisodeSourceModel.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
