// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MoviesHD.Model;
//
//    var movieModel = MovieModel.FromJson(jsonString);

namespace MoviesHD.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

   
    public class MovieSerialized
    {
        [JsonProperty("data")]
        public MovieSerializedData Data { get; set; }
    }
    
    public class MovieSerializedData
    {    

        public string id { get; set; }
        public string adjaraId { get; set; }
        public string originalName { get; set; }
public string secondaryName { get; set; }
        public string releaseDate { get; set; }
        public string imdbUrl { get; set; }
        public string isTvShow { get; set; }
        public string duration { get; set; }
        public string poster { get; set; }
        [JsonProperty("rating")]
        public Rating Rating { get; set; }
        [JsonProperty("countries")]
        public Countries Countries { get; set; }
        [JsonProperty("plot")]
        public Plot Plot { get; set; }

        [JsonProperty("plots")]
        public Plots Plots { get; set; }

        [JsonProperty("directors")]
        public Directors Directors { get; set; }
        public string ImdbUrl { get; set; }
        [JsonProperty("voters")]
        public long? Voters { get; set; }

        [JsonProperty("genres")]
        public Genres Genres { get; set; }

        [JsonProperty("seasons")]
        public Seasons Seasons { get; set; }



    }

    public class GenresData
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("primaryName")]
        public string PrimaryName { get; set; }

        [JsonProperty("secondaryName")]
        public string SecondaryName { get; set; }

        [JsonProperty("tertiaryName")]
        public string TertiaryName { get; set; }

        [JsonProperty("backgroundImage", NullValueHandling = NullValueHandling.Ignore)]
        public string BackgroundImage { get; set; }
    }
    public class Genres
    {
        [JsonProperty("data")]
        public List<GenresData> Data { get; set; }
    }






    public partial class MovieModel
    {
        [JsonProperty("data")]
        public MovieModelData Data { get; set; }
    }

    public partial class MovieModelData
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("adjaraId")]
        public long AdjaraId { get; set; }

        [JsonProperty("primaryName")]
        public string PrimaryName { get; set; }

        [JsonProperty("secondaryName")]
        public string SecondaryName { get; set; }

        [JsonProperty("tertiaryName")]
        public string TertiaryName { get; set; }

        [JsonProperty("originalName")]
        public string OriginalName { get; set; }

        [JsonProperty("year")]
        public long releaseDate { get; set; }

        [JsonProperty("releaseDate")]
        public DateTimeOffset ReleaseDate { get; set; }

        [JsonProperty("imdbUrl")]
        public Uri ImdbUrl { get; set; }

        [JsonProperty("isTvShow")]
        public bool IsTvShow { get; set; }

        [JsonProperty("budget")]
        public string Budget { get; set; }

        [JsonProperty("income")]
        public string Income { get; set; }

        [JsonProperty("duration")]
        public long Duration { get; set; }

        [JsonProperty("adult")]
        public bool Adult { get; set; }

        [JsonProperty("watchCount")]
        public long WatchCount { get; set; }

        [JsonProperty("canBePlayed")]
        public bool CanBePlayed { get; set; }

        [JsonProperty("cover")]
        public Cover Cover { get; set; }

        [JsonProperty("poster")]
        public string Poster { get; set; }

        [JsonProperty("rating")]
        public Rating Rating { get; set; }

        [JsonProperty("hasSubtitles")]
        public bool HasSubtitles { get; set; }

        [JsonProperty("languages")]
        public Languages Languages { get; set; }

        [JsonProperty("posters")]
        public Posters Posters { get; set; }

        [JsonProperty("covers")]
        public Covers Covers { get; set; }

        [JsonProperty("plot")]
        public Plot Plot { get; set; }

        [JsonProperty("plots")]
        public Plots Plots { get; set; }

        [JsonProperty("genres")]
        public Countries Genres { get; set; }

        [JsonProperty("trailers")]
        public AkaNames Trailers { get; set; }

        [JsonProperty("tvcom")]
        public Tvcom Tvcom { get; set; }

        [JsonProperty("countries")]
        public Countries Countries { get; set; }

        [JsonProperty("studios")]
        public AkaNames Studios { get; set; }

        [JsonProperty("seasons")]
        public Seasons Seasons { get; set; }

        [JsonProperty("vast")]
        public Vast Vast { get; set; }

        [JsonProperty("userWatch")]
        public UserWatch UserWatch { get; set; }

        [JsonProperty("userFollows")]
        public User UserFollows { get; set; }

        [JsonProperty("userWantsToWatch")]
        public User UserWantsToWatch { get; set; }

        [JsonProperty("userSubscribed")]
        public User UserSubscribed { get; set; }

        [JsonProperty("userMovieLists")]
        public AkaNames UserMovieLists { get; set; }

        [JsonProperty("userRating")]
        public UserRating UserRating { get; set; }

        [JsonProperty("directors")]
        public Directors Directors { get; set; }

        [JsonProperty("akaNames")]
        public AkaNames AkaNames { get; set; }

        [JsonProperty("oscarNominations")]
        public AkaNames OscarNominations { get; set; }
    }

    public partial class AkaNames
    {
        [JsonProperty("data")]
        public List<AkaNamesDatum> Data { get; set; }
    }

    public partial class AkaNamesDatum
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class Countries
    {
        [JsonProperty("data")]
        public List<CountriesDatum> Data { get; set; }
    }

    public partial class CountriesDatum
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("primaryName")]
        public string PrimaryName { get; set; }

        [JsonProperty("secondaryName")]
        public string SecondaryName { get; set; }

        [JsonProperty("tertiaryName")]
        public string TertiaryName { get; set; }

        [JsonProperty("backgroundImage", NullValueHandling = NullValueHandling.Ignore)]
        public string BackgroundImage { get; set; }
    }

    public partial class Cover
    {
        [JsonProperty("small")]
        public string Small { get; set; }

        [JsonProperty("large")]
        public string Large { get; set; }
    }

    public partial class Covers
    {
        [JsonProperty("data")]
        public Dictionary<string, Uri> Data { get; set; }
    }

    public partial class Directors
    {
        [JsonProperty("data")]
        public List<DirectorsDatum> Data { get; set; }
    }

    public partial class DirectorsDatum
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("originalName")]
        public string OriginalName { get; set; }

        [JsonProperty("primaryName")]
        public string PrimaryName { get; set; }

        [JsonProperty("secondaryName")]
        public string SecondaryName { get; set; }

        [JsonProperty("tertiaryName")]
        public string TertiaryName { get; set; }

        [JsonProperty("poster")]
        public Uri Poster { get; set; }

        [JsonProperty("birthDate")]
        public string BirthDate { get; set; }

        [JsonProperty("birthPlace")]
        public string BirthPlace { get; set; }

        [JsonProperty("deathDate")]
        public string DeathDate { get; set; }

        [JsonProperty("deathPlace")]
        public string DeathPlace { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }

        [JsonProperty("slogan")]
        public string Slogan { get; set; }

        [JsonProperty("zodiacSign")]
        public string ZodiacSign { get; set; }
    }

    public partial class Languages
    {
        [JsonProperty("data")]
        public List<LanguagesDatum> Data { get; set; }
    }

    public partial class LanguagesDatum
    {
        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("primaryName")]
        public string PrimaryName { get; set; }

        [JsonProperty("primaryNameTurned")]
        public string PrimaryNameTurned { get; set; }

        [JsonProperty("tertiaryName")]
        public string TertiaryName { get; set; }

        [JsonProperty("secondaryName")]
        public string SecondaryName { get; set; }
    }

    public partial class Plot
    {
        [JsonProperty("data")]
        public Dat Data { get; set; }
    }

    public partial class Dat
    {
        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("language")]
        public string Language { get; set; }
    }

    public partial class Plots
    {
        [JsonProperty("data")]
        public List<Dat> Data { get; set; }
    }

    public partial class Posters
    {
        [JsonProperty("data")]
        public PostersData Data { get; set; }
    }

    public partial class PostersData
    {
        [JsonProperty("240")]
        public Uri The240 { get; set; }
    }

    public partial class Rating
    {
        [JsonProperty("imovies")]
        public Imdb Imovies { get; set; }

        [JsonProperty("imdb")]
        public Imdb Imdb { get; set; }

        [JsonProperty("rotten")]
        public Imdb Rotten { get; set; }

        [JsonProperty("metacritic")]
        public Imdb Metacritic { get; set; }
    }

    public partial class Imdb
    {
        [JsonProperty("score")]
        public double Score { get; set; }

        [JsonProperty("voters")]
        public long? Voters { get; set; }
    }

    public partial class Seasons
    {
        [JsonProperty("data")]
        public List<SeasonsDatum> Data { get; set; }
    }

    public partial class SeasonsDatum
    {
        [JsonProperty("movieId")]
        public long MovieId { get; set; }

        [JsonProperty("number")]
        public long Number { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("episodesCount")]
        public long EpisodesCount { get; set; }
    }

    public partial class Tvcom
    {
        [JsonProperty("data")]
        public TvcomData Data { get; set; }
    }

    public partial class TvcomData
    {
        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public partial class User
    {
        [JsonProperty("data")]
        public UserFollowsData Data { get; set; }
    }

    public partial class UserFollowsData
    {
        [JsonProperty("status")]
        public bool Status { get; set; }
    }

    public partial class UserRating
    {
        [JsonProperty("data")]
        public UserRatingData Data { get; set; }
    }

    public partial class UserRatingData
    {
        [JsonProperty("status")]
        public bool Status { get; set; }

        [JsonProperty("rate")]
        public long Rate { get; set; }
    }

    public partial class UserWatch
    {
        [JsonProperty("data")]
        public UserWatchData Data { get; set; }
    }

    public partial class UserWatchData
    {
        [JsonProperty("season")]
        public object Season { get; set; }

        [JsonProperty("episode")]
        public object Episode { get; set; }

        [JsonProperty("language")]
        public string Language { get; set; }

        [JsonProperty("quality")]
        public string Quality { get; set; }

        [JsonProperty("progress")]
        public long Progress { get; set; }

        [JsonProperty("duration")]
        public long Duration { get; set; }

        [JsonProperty("visible")]
        public bool Visible { get; set; }

        [JsonProperty("updateDate")]
        public string UpdateDate { get; set; }

        [JsonProperty("watched")]
        public bool Watched { get; set; }
    }

    public partial class Vast
    {
        [JsonProperty("data")]
        public VastData Data { get; set; }
    }

    public partial class VastData
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("pause_url")]
        public string PauseUrl { get; set; }
    }

    public partial class MovieModel
    {
        public static MovieModel FromJson(string json) => JsonConvert.DeserializeObject<MovieModel>(json, MoviesHD.Model.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this MovieModel self) => JsonConvert.SerializeObject(self, MoviesHD.Model.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
